### ISSUE TITLE
digital.me basic version is working & can be used by developers

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#16]
## goals

- [ ] easy for anyone on development jumpscale machine on osx/linux to start X nr of DM's
- [ ] ipv6 support
- [ ] each DM get's registered in zerotier on ipv6 (1d7193940435f485) = autoasign is on
    - [ ] ipv6 & multicast support
- [ ] each DM owner can create groups in his circle (DNS domains of $min5char.$min5char)
- [ ] each DM has DNS running inside which exposes all known circle domains
- [ ] each user in the DM network has a primary DM which hosts his/her identity 
    - [ ] user/group mgmt implemented in BCDB/Gedis #19
- [ ] ACL's can be given on each data object in DM in BCDB (database in DM) #19
- [ ] DM's can super easily talk to each other to fetch relevant info
- [x] DM's can host our wiki's
    - [ ] wiki documented
- [ ] DM also has oauthv2 inside #17
- [x] example websites created (2x): #7 
- [ ] rqueue inside & documented how to use: #2
- [ ] rivine explorer inside & talks to internal hosted rivined
- [x] TF website inside using flask & templates & markdown #9 
- [ ] zero-hub inside 
- [ ] orderbook working
- [x] interfaces defined for farmer robot = gedis interface #18

## implementation remarks

- DM's do multicast to announce to each other, each DM build up own DB & remembers Pub Key
- in this story card all running in development mode, for production see #15
- BCDB supports indexing (sqlite-peewee based prob)
- chat feature works to DM

- [ ] runs using sandbox js95 [sandbox story]()

**Comment by despiegk** [comment]
see with kristof for next steps
needs https://github.com/threefoldtech/jumpscale_lib/issues/92 finished

**Comment by rkhamis** [comment]
https://github.com/threefoldtech/jumpscale_lib/issues/92 is done
